package logic;

public enum State {

	DATABASE_ERROR, BACKEND_USER, FRONTEND_USER, INVALID_USER, FLEXDRIVE_REGISTERED, FLEXDRIVE_BOOKED, FLEXDRIVE_APPROVED, USER_CREATED,
	USER_UPDATED, BOOKED_FAILED;

}
