package logic;

public enum ValidationErrors {
	
	BOOKED_FOR_ERROR, PASSENGERS_ERROR, ADDRESS_FROM_ERROR, ADDRESS_TO_ERROR,
	CHILD_CAR_SEAT_ASSISTIVE_QTY_ERROR, USERNAME_REQUIRED_ERROR, PASSWORD_REQUIRED_ERROR,
	PHONE_NUMBER_LENGTH_ERROR, CPR_NUMBER_LENGTH_ERROR;
	
}
